### ISSUE TITLE
When Spectating: Opponents items sometimes appear in main player's items

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#121]
Spectator only bug so hard to reproduce:

As main player (me logged in):
![image](https://user-images.githubusercontent.com/5060535/209628943-05b83088-6ebe-4a1b-9e32-02950763be60.png)

As other player (as a guest):
<img width="776" alt="image" src="https://user-images.githubusercontent.com/5060535/209628973-a1b15cb1-a7ed-434f-88fb-89d9604ba89f.png">

As spectator:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/5060535/209629008-ccda79db-f55d-4d98-bc06-5c30e9e15dc3.png">

Game number for ref:
432253

**Comment by OotTheMonk** [comment]
Was not able to reproduce. Tried on local and on live server, with various hold priority settings. Also tried pulling the gamestate from the bug report, but it's from before the breaking change made to fix oasis respite, so it doesn't work.

May have been fixed already by combining the old gamestate parsing into the one that was a function and created for replays.

**Comment by LaustinSpayce** [comment]
<img width="1535" alt="image" src="https://user-images.githubusercontent.com/5060535/212549689-2a5135f8-08e6-4b06-a8b7-ac5fb085f66a.png">

Just now from a game. The bug still lurks out there.

**Comment by OotTheMonk** [comment]
Fixed by deba9a41
